# Generated by Django 6.0.3 on 2026-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='donate_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
